teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 3
        target: linear.x
        scale: 1
      -
        axis: 2
        target: angular.z
        scale: 1
